apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-deploy
spec:
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: mc01
        image: memcached:latest
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: mc01
spec:
  selector:
    app: memcached
  ports:
  - port: 11211
