
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rmq01
        image: rabbitmq:latest
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              name: roma
              key: rmq_user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: roma
              key: test
---
apiVersion: v1
kind: Service
metadata:
  name: rmq01
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
