---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piemonte
  labels:
    speed: fast
    redundant: geo
provisioner: disk.csi.azure.com
parameters:
  location: koreacentral
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
